import React, { useEffect, useState } from 'react';
import { event } from '../data/event';
import { supabase } from '../lib/supabaseClient';

const roles = ['participant', 'presenter', 'observer', 'oak_staff', 'coordination_team', 'admin'];

export default function AdminPage() {
  const [participants, setParticipants] = useState([]); const [profiles, setProfiles] = useState({}); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { const [{ data: people, error: peopleError }, { data: rolesData, error: rolesError }] = await Promise.all([supabase.from('participants').select('id,user_id,first_name,last_name,email,organization,role,registered_at').eq('event_id', event.id).order('registered_at', { ascending: false }), supabase.from('profiles').select('id,app_role')]); if (peopleError || rolesError) setError(peopleError?.message || rolesError?.message); else { setParticipants(people); setProfiles(Object.fromEntries(rolesData.map((item) => [item.id, item.app_role]))); } };
  useEffect(() => { load(); }, []);
  const promote = async (userId, appRole) => { setMessage(''); const { error: requestError } = await supabase.rpc('admin_set_app_role', { p_user_id: userId, p_role: appRole }); if (requestError) setError(requestError.message); else { setMessage('Role updated.'); load(); } };
  const addSession = async (form) => { const data = new FormData(form); const { error: requestError } = await supabase.from('sessions').insert({ event_id: event.id, title: data.get('title'), starts_at: data.get('starts_at'), ends_at: data.get('ends_at'), speaker: data.get('speaker') || null, venue: data.get('venue') || null, description: data.get('description') || null }); if (requestError) setError(requestError.message); else { setMessage('Session published.'); form.reset(); } };
  const addPartner = async (form) => { const data = new FormData(form); const { error: requestError } = await supabase.from('partners').insert({ event_id: event.id, name: data.get('name'), description: data.get('description') || null, website_url: data.get('website_url') || null, contact_name: data.get('contact_name') || null, contact_email: data.get('contact_email') || null, areas_of_work: data.get('areas_of_work').split(',').map((item) => item.trim()).filter(Boolean) }); if (requestError) setError(requestError.message); else { setMessage('Partner published.'); form.reset(); } };
  return <div className="reference-page internal-page"><main className="attendance-wrap"><header className="split-heading"><div><span className="eyebrow">EVENT ADMINISTRATION</span><h1>Manage event</h1><p>Publish content and approve access for {event.name}.</p></div></header>{error && <p className="camera-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}<section className="reference-card registration-form"><h2>Publish a session</h2><form onSubmit={(item) => { item.preventDefault(); addSession(item.currentTarget); }}><Field label="Title" name="title" required /><Field label="Starts" name="starts_at" type="datetime-local" required /><Field label="Ends" name="ends_at" type="datetime-local" required /><Field label="Speaker" name="speaker" /><Field label="Venue" name="venue" /><Field label="Description" name="description" /><button className="primary-button">Publish session</button></form></section><section className="reference-card registration-form"><h2>Publish a partner</h2><form onSubmit={(item) => { item.preventDefault(); addPartner(item.currentTarget); }}><Field label="Organisation name" name="name" required /><Field label="Areas of work" name="areas_of_work" placeholder="Climate, Human rights" required /><Field label="Website URL" name="website_url" type="url" /><Field label="Contact name" name="contact_name" /><Field label="Contact email" name="contact_email" type="email" /><Field label="Description" name="description" /><button className="primary-button">Publish partner</button></form></section><section className="arrivals-card reference-card"><header><div><h2>Registrant access</h2><p>Assign operational roles only to trusted people.</p></div></header>{participants.map((person) => <div className="arrival-row" key={person.id}><span className="avatar">{person.first_name[0]}{person.last_name[0]}</span><span><strong>{person.first_name} {person.last_name}</strong><small>{person.email} · Registered as {person.role}</small></span><select value={profiles[person.user_id] || 'participant'} onChange={(item) => promote(person.user_id, item.target.value)}>{roles.map((role) => <option key={role} value={role}>{role.replace('_', ' ')}</option>)}</select></div>)}</section></main></div>;
}
function Field({ label, ...props }) { return <label className="form-field"><span>{label}</span><input {...props} /></label>; }
