import React, { useEffect, useMemo, useRef, useState } from 'react';
import { BrowserQRCodeReader } from '@zxing/browser';
import { AlertTriangle, Camera, Check, CircleCheck, Clock3, HelpCircle, Search, ShieldCheck, VideoOff } from 'lucide-react';
import { getProfile, recordCheckin } from '../data/store';

const attendees = [{ initials: 'MS', name: 'Maria Schmidt', detail: 'Global Health Initiative · Partner', tag: 'Partner', id: 'OAK-2026-8492' }, { initials: 'JO', name: 'James Okhabo', detail: 'OAK Foundation · OAK Staff', tag: 'OAK Staff', id: 'OAK-2026-2107' }, { initials: 'AD', name: 'Ava Diallo', detail: 'West Africa Network · Coordination Team', tag: 'Coordination Team', id: 'OAK-2026-6731' }, { initials: 'FZ', name: 'Fatima Z. Benali', detail: 'Morocco Civic Forum · Partner', tag: 'Partner', id: 'OAK-2026-4156' }];

const attendeeFromCode = (value) => {
  const profile = getProfile();
  const own = { initials: `${profile.firstName[0] || ''}${profile.lastName[0] || ''}`, name: `${profile.firstName} ${profile.lastName}`, detail: `${profile.organisation} · ${profile.role}`, tag: profile.role, id: profile.id };
  return [own, ...attendees].find((person) => value.toUpperCase().includes(person.id.toUpperCase()));
};

export default function CheckInPage({ initialStatus = 'scanning' }) {
  const [code, setCode] = useState(''); const [checkedIn, setCheckedIn] = useState([]); const [status, setStatus] = useState(initialStatus); const [current, setCurrent] = useState(null); const [cameraActive, setCameraActive] = useState(false); const [cameraError, setCameraError] = useState('');
  const videoRef = useRef(null); const controlsRef = useRef(null);
  const available = useMemo(() => attendees.filter(person => !checkedIn.includes(person.id)), [checkedIn]);
  const stopCamera = () => { controlsRef.current?.stop(); controlsRef.current = null; setCameraActive(false); };
  const approve = (person) => { if (!person) { stopCamera(); return setStatus('error'); } stopCamera(); setCurrent(person); setCheckedIn(items => items.includes(person.id) ? items : [...items, person.id]); recordCheckin(person); setStatus('success'); };
  const startCamera = async () => { setCameraError(''); try { const reader = new BrowserQRCodeReader(); controlsRef.current = await reader.decodeFromVideoDevice(undefined, videoRef.current, (result) => { if (result) approve(attendeeFromCode(result.getText())); }); setCameraActive(true); } catch { setCameraError('Camera access was not available. Allow camera access, then try again or use the manual code entry.'); } };
  const reset = () => { stopCamera(); setStatus('scanning'); setCurrent(null); setCode(''); };
  const submitCode = (event) => { event.preventDefault(); approve(attendeeFromCode(code.trim())); };
  useEffect(() => () => controlsRef.current?.stop(), []);
  return <div className="reference-page internal-page"><main className="event-checkin"><header className="checkin-title"><h1>Event Check-In</h1><p>Scan an attendee QR code to check them in.</p></header>{status === 'success' ? <Success person={current} onNext={reset} /> : status === 'error' ? <Failure onRetry={reset} /> : <><section className={`event-scanner ${cameraActive ? 'camera-active' : ''}`}><video ref={videoRef} muted playsInline /><div className="event-frame"><span className="corner top-left" /><span className="corner top-right" /><span className="corner bottom-left" /><span className="corner bottom-right" /></div>{!cameraActive && <button className="camera-start" onClick={startCamera}><Camera /> Start camera</button>}<span className="frame-hint">{cameraActive ? 'Point the camera at a valid OAK QR code' : 'Use the live camera or enter a pass code below'}</span><footer><i /> {cameraActive ? 'Scanning for QR codes…' : 'Camera stays off until you start it'}</footer></section>{cameraError && <p className="camera-error"><VideoOff /> {cameraError}</p>}<section className="scan-list"><p className="scan-label">AVAILABLE FOR SCAN</p>{available.length ? available.map(person => <button key={person.id} className="scan-person" onClick={() => approve(person)}><span className="scan-avatar">{person.initials}</span><span><strong>{person.name}</strong><small>{person.detail}</small></span><em className={person.tag.toLowerCase().replaceAll(' ', '-')}>{person.tag}</em></button>) : <div className="all-scanned"><Check /> All displayed attendees are checked in.</div>}</section><form className="code-entry" onSubmit={submitCode}><p className="scan-label">MANUAL CODE ENTRY</p><div><input value={code} onChange={event => setCode(event.target.value)} placeholder="OAK-2026-XXXX" /><button aria-label="Check in code"><Search /></button></div></form></>}</main></div>;
}

function Success({ person, onNext }) { return <section className="check-status success-status"><header><CircleCheck /><span><strong>Checked In Successfully</strong><small>Attendee is now marked as present</small></span></header><article className="status-person"><span className="status-avatar">{person.initials}</span><div><strong>{person.name}</strong><small>{person.detail}</small><em>{person.tag}</em></div></article><div className="status-summary"><span><Clock3 /><div><small>CHECK-IN TIME</small><strong>Just now</strong></div></span><span><ShieldCheck /><div><small>PASS STATUS</small><strong>Verified</strong></div></span></div><div className="status-tip good"><Check /> Entry pass verified. Please welcome the attendee to the event.</div><button className="status-action" onClick={onNext}>Scan Next Attendee</button></section>; }
function Failure({ onRetry }) { return <section className="check-status error-status"><header><AlertTriangle /><span><strong>QR Not Recognised</strong><small>We couldn’t verify this attendee pass</small></span></header><div className="status-tip bad"><HelpCircle /> Possible reasons<div><span>• QR code has expired or is invalid</span><span>• Registration has been cancelled</span><span>• Attendee has already checked in</span></div></div><button className="status-action" onClick={onRetry}>Try Again</button><button className="support-action" onClick={onRetry}>Return to scanner</button></section>; }
