import React, { useMemo, useState } from 'react';
import { AlertTriangle, Camera, Check, CircleCheck, Clock3, HelpCircle, Search, ShieldCheck } from 'lucide-react';

const attendees = [{ initials: 'MS', name: 'Maria Schmidt', detail: 'Global Health Initiative · Partner', tag: 'Partner', id: 'OAK-2026-8492' }, { initials: 'JO', name: 'James Okhabo', detail: 'OAK Foundation · OAK Staff', tag: 'OAK Staff', id: 'OAK-2026-2107' }, { initials: 'AD', name: 'Ava Diallo', detail: 'West Africa Network · Coordination Team', tag: 'Coordination Team', id: 'OAK-2026-3294' }, { initials: 'FZ', name: 'Fatima Z. Benali', detail: 'Morocco Civic Forum · Partner', tag: 'Partner', id: 'OAK-2026-4156' }];

export default function CheckInPage({ initialStatus = 'scanning' }) {
  const [code, setCode] = useState(''); const [checkedIn, setCheckedIn] = useState([]); const [status, setStatus] = useState(initialStatus); const [current, setCurrent] = useState(null);
  const available = useMemo(() => attendees.filter(person => !checkedIn.includes(person.name)), [checkedIn]);
  const reset = () => { setStatus('scanning'); setCurrent(null); setCode(''); };
  const approve = (person) => { if (!person) return setStatus('error'); setCurrent(person); setCheckedIn(items => items.includes(person.name) ? items : [...items, person.name]); setStatus('success'); };
  const submitCode = (event) => { event.preventDefault(); const match = attendees.find(person => person.id.toLowerCase() === code.trim().toLowerCase()); match ? approve(match) : setStatus('error'); };
  return <div className="reference-page internal-page"><main className="event-checkin"><header className="checkin-title"><h1>Event Check-In</h1><p>Scan an attendee QR code to check them in.</p></header>{status === 'success' ? <Success person={current || attendees[0]} onNext={reset} /> : status === 'error' ? <Failure onRetry={reset} /> : <><section className="event-scanner"><div className="event-frame"><span className="corner top-left" /><span className="corner top-right" /><span className="corner bottom-left" /><span className="corner bottom-right" /></div><Camera /><span className="frame-hint">Position QR code within the frame</span><footer><i /> Hold camera steady · Auto-scan in 1–2 seconds</footer></section><section className="scan-list"><p className="scan-label">AVAILABLE FOR SCAN</p>{available.length ? available.map(person => <button key={person.name} className="scan-person" onClick={() => approve(person)}><span className="scan-avatar">{person.initials}</span><span><strong>{person.name}</strong><small>{person.detail}</small></span><em className={person.tag.toLowerCase().replaceAll(' ', '-')}>{person.tag}</em></button>) : <div className="all-scanned"><Check /> All displayed attendees are checked in.</div>}</section><form className="code-entry" onSubmit={submitCode}><p className="scan-label">MANUAL CODE ENTRY</p><div><input value={code} onChange={event => setCode(event.target.value)} placeholder="OAK-2026-XXXX-XXXX" /><button aria-label="Check in code"><Search /></button></div></form></>}</main></div>;
}

function Success({ person, onNext }) { return <section className="check-status success-status"><header><CircleCheck /><span><strong>Checked In Successfully</strong><small>Attendee is now marked as present</small></span></header><article className="status-person"><span className="status-avatar">{person.initials}</span><div><strong>{person.name}</strong><small>{person.detail}</small><em>{person.tag}</em></div></article><div className="status-summary"><span><Clock3 /><div><small>CHECK-IN TIME</small><strong>Just now</strong></div></span><span><ShieldCheck /><div><small>PASS STATUS</small><strong>Verified</strong></div></span></div><div className="status-tip good"><Check /> Entry pass verified. Please welcome the attendee to the event.</div><button className="status-action" onClick={onNext}>Scan Next Attendee</button></section> }
function Failure({ onRetry }) { return <section className="check-status error-status"><header><AlertTriangle /><span><strong>QR Not Recognised</strong><small>We couldn’t verify this attendee pass</small></span></header><div className="status-tip bad"><HelpCircle /> Possible reasons<div><span>• QR code has expired or is invalid</span><span>• Registration has been cancelled</span><span>• Attendee has already checked in</span></div></div><button className="status-action" onClick={onRetry}>Try Again</button><button className="support-action" onClick={onRetry}>Contact Event Team</button></section> }
