import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, ExternalLink, Globe2, Mail, Search } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { event } from '../data/event';
import { getPartners } from '../lib/eventApi';

const initials = (name) => name.split(' ').map((word) => word[0]).join('').slice(0, 3).toUpperCase();
function Initials({ children }) { return <span className="partner-initials">{children}</span>; }

export default function PartnersPage() {
  const navigate = useNavigate(); const { partnerId } = useParams(); const [partners, setPartners] = useState([]); const [query, setQuery] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getPartners(event.id).then(setPartners).catch((err) => setError(err.message)); }, []);
  const selected = partners.find((partner) => partner.id === partnerId);
  const visible = useMemo(() => partners.filter((partner) => `${partner.name} ${partner.description || ''} ${(partner.areas_of_work || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [partners, query]);
  if (selected) return <div className="reference-page"><main className="partner-detail reference-column"><button className="reference-back" onClick={() => navigate('/partners')}><ArrowLeft /> Partner Directory</button><section className="partner-hero"><Initials>{initials(selected.name)}</Initials><div><p>EVENT PARTNER</p><h1>{selected.name}</h1></div><div className="partner-tags">{(selected.areas_of_work || []).map((tag) => <span key={tag}>{tag}</span>)}</div></section><section className="reference-card partner-about"><p className="reference-label">ABOUT</p><p>{selected.description || 'Profile coming soon.'}</p></section><section className="reference-card partner-contact"><p className="reference-label">CONTACT</p><div><Initials>{initials(selected.contact_name || selected.name)}</Initials><span><strong>{selected.contact_name || 'Contact to be confirmed'}</strong><small>{selected.contact_email || ''}</small></span></div></section>{selected.website_url && <a className="partner-primary-action" href={selected.website_url} target="_blank" rel="noreferrer"><Globe2 /> Visit website <ExternalLink /></a>}{selected.contact_email && <a className="partner-message-action" href={`mailto:${selected.contact_email}`}><Mail /> Send message <ChevronRight /></a>}</main></div>;
  return <div className="reference-page"><main className="reference-column partner-directory"><header><h1>Partner Directory</h1><p>{partners.length} partner organisations</p></header><section className="reference-card directory-filters"><label><Search /><input value={query} onChange={(item) => setQuery(item.target.value)} placeholder="Search organisations or focus areas..." /></label></section>{error && <p className="camera-error" role="alert">{error}</p>}<p className="reference-label">ALL PARTNERS</p><section className="partner-list">{visible.map((partner) => <button key={partner.id} onClick={() => navigate(`/partners/${partner.id}`)} className="reference-card partner-row"><Initials>{initials(partner.name)}</Initials><span className="partner-row-copy"><strong>{partner.name}</strong><small>{partner.contact_name || 'Event partner'}</small><span className="partner-tags">{(partner.areas_of_work || []).map((tag) => <em key={tag}>{tag}</em>)}</span></span><ChevronRight /></button>)}{!error && !visible.length && <p className="empty-notes">No partners have been published yet.</p>}</section></main></div>;
}
