import React, { useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, ExternalLink, Globe2, Mail, Search } from 'lucide-react';

const partners = [
  { id: 1, initials: 'OSF', name: 'Open Society Foundations', region: 'Global', since: '2018', tags: ['Foundation', 'Democracy', 'Human Rights'], website: 'opensocietyfoundations.org', about: 'Open Society Foundations builds vibrant and tolerant democracies. OAK partnership covers digital rights and justice initiatives across Eastern Europe and Central Asia.', contact: 'Maria Schmidt', email: 'm.schmidt@osf.org' },
  { id: 2, initials: 'ACA', name: 'Africa Climate Alliance', region: 'Sub-Saharan Africa', since: '2020', tags: ['NGO', 'Climate Justice', 'Youth Advocacy'], website: 'africaclimatealliance.org', about: 'Africa Climate Alliance supports youth-led action and community solutions for a just climate transition.', contact: 'Tariro Moyo', email: 't.moyo@aca.org' },
  { id: 3, initials: 'NEC', name: 'Nordic Evaluation Centre', region: 'Northern Europe', since: '2021', tags: ['Research', 'Evaluation', 'Learning'], website: 'nordicevaluation.org', about: 'Nordic Evaluation Centre brings practical evidence and learning to social-impact programmes.', contact: 'Lina Berg', email: 'l.berg@nec.org' },
  { id: 4, initials: 'MRG', name: 'MENA Rights Group', region: 'Middle East & North Africa', since: '2019', tags: ['NGO', 'Human Rights', 'Documentation'], website: 'menarights.org', about: 'MENA Rights Group documents rights concerns and supports advocacy for dignity and accountability.', contact: 'Nadia Saleh', email: 'n.saleh@mrg.org' },
  { id: 5, initials: 'DFI', name: 'Digital Frontiers Institute', region: 'Global / Africa', since: '2022', tags: ['Research', 'Digital Rights', 'Internet Freedom'], website: 'digitalfrontiers.org', about: 'Digital Frontiers Institute researches and advances open, inclusive digital spaces.', contact: 'Kofi Mensah', email: 'k.mensah@dfi.org' },
  { id: 6, initials: 'GAL', name: 'Global Advocacy Lab', region: 'Global', since: '2023', tags: ['NGO', 'Communications', 'Campaigns'], website: 'globaladvocacylab.org', about: 'Global Advocacy Lab builds campaigns that connect research, communities, and public action.', contact: 'Ana Torres', email: 'a.torres@gal.org' },
  { id: 7, initials: 'SP', name: 'Sciences Po Paris', region: 'Western Europe', since: '2020', tags: ['Academic', 'Research', 'Policy'], website: 'sciencespo.fr', about: 'Sciences Po Paris contributes policy research and learning partnerships to the convening.', contact: 'Camille Dubois', email: 'c.dubois@sciencespo.fr' },
  { id: 8, initials: 'EFG', name: 'Environmental Funders Group', region: 'Europe', since: '2021', tags: ['Network', 'Environment', 'Climate'], website: 'environmentalfunders.org', about: 'Environmental Funders Group connects funders and partners focused on climate and environmental action.', contact: 'James Cole', email: 'j.cole@efg.org' },
];
const regions = ['All Regions', 'Global', 'Sub-Saharan Africa', 'Northern Europe', 'Middle East & North Africa'];
function Initials({ children, muted = false }) { return <span className={`partner-initials ${muted ? 'muted' : ''}`}>{children}</span>; }

export default function PartnersPage({ initialPartnerId = null }) {
  const [selected, setSelected] = useState(() => partners.find((partner) => partner.id === initialPartnerId) || null);
  const [query, setQuery] = useState(''); const [region, setRegion] = useState('All Regions');
  const visible = useMemo(() => partners.filter((partner) => `${partner.name} ${partner.region} ${partner.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (region === 'All Regions' || partner.region.includes(region))), [query, region]);
  if (selected) return <div className="reference-page"><main className="partner-detail reference-column"><button className="reference-back" onClick={() => setSelected(null)}><ArrowLeft /> Partner Directory</button><section className="partner-hero"><Initials>{selected.initials}</Initials><div><p>FOUNDATION · PARTNER SINCE {selected.since}</p><h1>{selected.name}</h1></div><div className="partner-tags">{selected.tags.slice(1).map((tag) => <span key={tag}>{tag}</span>)}</div></section><section className="reference-card partner-about"><p className="reference-label">ABOUT</p><p>{selected.about}</p></section><section className="reference-card partner-contact"><p className="reference-label">CONTACT AT CONVENING</p><div><Initials>{selected.contact.split(' ').map((word) => word[0]).join('')}</Initials><span><strong>{selected.contact}</strong><small>{selected.email}</small></span></div></section><a className="partner-primary-action" href={`https://${selected.website}`}><Globe2 /> Visit Website <ExternalLink /></a><a className="partner-message-action" href={`mailto:${selected.email}`}><Mail /> Send Message <ChevronRight /></a></main></div>;
  return <div className="reference-page"><main className="reference-column partner-directory"><header><h1>Partner Directory</h1><p>8 partner organisations</p></header><section className="reference-card directory-filters"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search organisations, focus areas..." /></label><div>{regions.map((item) => <button key={item} onClick={() => setRegion(item)} className={region === item ? 'selected' : ''}>{item}</button>)}</div></section><p className="reference-label">SUB-PARTNERS</p><section className="partner-highlights">{partners.slice(0, 3).map((partner) => <button key={partner.id} onClick={() => setSelected(partner)}><Initials>{partner.initials}</Initials><strong>{partner.initials}</strong><small>{partner.region}</small></button>)}</section><p className="reference-label">ALL PARTNERS</p><section className="partner-list">{visible.map((partner) => <button key={partner.id} onClick={() => setSelected(partner)} className="reference-card partner-row"><Initials muted={partner.id === 7}>{partner.initials}</Initials><span className="partner-row-copy"><strong>{partner.name}</strong><small>{partner.region}</small><span className="partner-tags">{partner.tags.map((tag) => <em key={tag}>{tag}</em>)}</span></span><ChevronRight /><footer><span>Partner since {partner.since}</span><span>{partner.website} <ExternalLink /></span></footer></button>)}</section></main></div>;
}
