import React, { useState } from 'react';
import { CalendarDays, ChevronDown, Download, FileText, Image, MapPin, NotebookPen } from 'lucide-react';

const schedule = [
  { time: '08:00', kind: 'quiet', title: 'Registration & Welcome Coffee' }, { time: '10:30', kind: 'quiet', title: 'Coffee Break' },
  { time: '10:50', kind: 'breakout', title: 'Thematic Dialogue: Climate Justice & Grantmaking', detail: 'Samuel Okafor · Africa Climate Alliance', room: 'Conference Room B2' },
  { time: '12:00', kind: 'workshop', title: 'Workshop: Measuring Long-term Change', detail: 'Dr. Ingrid Holm · Nordic Evaluation Centre', room: 'Workshop Room C' },
  { time: '12:00', kind: 'quiet', title: 'Networking Lunch' }, { time: '13:30', kind: 'plenary', title: 'Partner Spotlight: Rights-Based Approaches', detail: 'Fatima Zahra Benali · MENA Rights Group', room: 'Main Hall A1' },
  { time: '14:45', kind: 'breakout', title: 'Digital Rights in Authoritarian Contexts', detail: 'Lina Wei · Digital Frontiers Institute', room: 'Conference Room D1' },
  { time: '18:00', kind: 'social', title: 'Welcome Reception & Dinner', detail: '', room: 'Rooftop Terrace' }
];
const notes = [{ title: 'Maria Schmidt', body: 'The most shared approaches were selected during dinner as a shared learning platform. Our OAK fellows will take these ideas forward in joint programming conversations.' }, { title: 'Tariro Moyo', body: 'Our long-term measurement approach is working group to share tools for practical implementation and common measurement challenges across partners.' }, { title: 'Lina Chen', body: 'Strong communication networks might be North Africa’s adaptive message framework to directly collaborate across OAK’s partner organizations.' }, { title: 'Amina A. Kone', body: 'Partners raised common pathways with an updated grant timeline. We will continue reviewing new forms of best practice.' }];
const resources = ['Opening Plenary Presentation', 'OAK Portfolio Overview 2026–28', 'Action Planning Worksheet', 'Partner Contact Directory', 'Photo Gallery: Day 1'];
const badge = (kind) => ({ breakout: 'Breakout', workshop: 'Workshop', plenary: 'Plenary', social: 'Social' }[kind]);

export default function ProgramPage() { const [tab, setTab] = useState('schedule'); const [day, setDay] = useState(1); return <div className="reference-page"><main className="programme-reference"><header className="programme-header"><h1>Programme</h1><p>OAK Partner Convening 2026</p><div className="programme-tabs"><button className={tab === 'schedule' ? 'active' : ''} onClick={() => setTab('schedule')}>Schedule</button><button className={tab === 'docs' ? 'active' : ''} onClick={() => setTab('docs')}>Docs</button></div></header>{tab === 'schedule' ? <Schedule day={day} setDay={setDay} /> : <Documents />}</main></div>; }

function Schedule({ day, setDay }) { return <><section className="programme-days">{[1, 2, 3].map(number => <button key={number} onClick={() => setDay(number)} className={day === number ? 'active' : ''}><small>{number === 1 ? 'MON' : number === 2 ? 'TUE' : 'WED'}</small><strong>Day {number}</strong><span>{8 + number} Mar</span></button>)}</section>{day === 1 ? <><section className="featured-session"><small>★ FEATURED &nbsp;&nbsp; · &nbsp;&nbsp; 08:00–10:30</small><h2>Opening Plenary: Pathways to Impact</h2><p>Dr. Helena Murewa · OAK Foundation</p><span><MapPin /> Main Hall A</span></section><div className="programme-legend"><span className="plenary">● Plenary</span><span className="breakout">● Breakout</span><span className="workshop">● Workshop</span><span className="social">● Social</span></div><section className="timeline">{schedule.map((item, index) => item.kind === 'quiet' ? <div className="quiet-item" key={index}><time>{item.time}</time><span>{item.title}</span></div> : <article className="agenda-card" key={index}><time>{item.time}<small>–{index === 7 ? '20:00' : index === 6 ? '18:00' : index === 5 ? '14:30' : index === 4 ? '15:30' : index === 3 ? '13:00' : index === 2 ? '12:00' : '11:50'}</small></time><div><h3>{item.title}</h3>{item.detail && <p>{item.detail}</p>}<span><MapPin /> {item.room}</span></div><em className={item.kind}>{badge(item.kind)} <ChevronDown /></em></article>)}</section></> : <section className="empty-day"><CalendarDays /><h2>Day {day} agenda</h2><p>The detailed agenda will be shared shortly.</p></section>}</> }

function Documents() { return <section className="docs-view"><div className="docs-heading"><span><FileText /> Session Notes</span><button>+ Add note</button></div>{notes.map((note, index) => <article className="note-card" key={note.title}><span className="note-avatar">{note.title.split(' ').map(word => word[0]).join('')}</span><div><strong>{note.title}</strong><small>{index + 1}h ago</small><p>{note.body}</p></div></article>)}<div className="docs-section-title"><Image /> Photo Gallery <small>6 photos</small></div><div className="photo-grid">{Array.from({ length: 6 }, (_, index) => <div className={`photo photo-${index + 1}`} key={index} />)}</div><div className="docs-section-title"><NotebookPen /> Key Takeaways</div><article className="takeaways">{['Partnership needs to accept the year into horizons for systems change.', 'Shared learning infrastructure is the most requested resource across the convening.', 'Digital rights must be integrated into all programme areas, not siloed.', 'Rights-based funding effectively improves partner advocacy effectiveness.', 'Peer exchange is the most valued support across OAK’s NGO network.'].map(item => <p key={item}>● <span>{item}</span></p>)}</article><div className="docs-section-title"><FileText /> Resources</div><div className="resource-list">{resources.map((resource, index) => <button key={resource}><FileText /><span><strong>{resource}</strong><small>{index === 4 ? '12 photos · added today' : 'PDF · 1.4 MB · added today'}</small></span><Download /></button>)}</div></section> }
