import React, { useState } from 'react';
import { ChevronDown, Download, FileText, Image, MapPin, NotebookPen } from 'lucide-react';

const programmes = {
  1: [{ time: '08:00', end: '10:30', kind: 'plenary', title: 'Opening Plenary: Pathways to Impact', detail: 'Dr. Helena Murewa · OAK Foundation', room: 'Main Hall A', description: 'A shared opening on priorities, collaboration, and the practical agenda for the convening.' }, { time: '10:50', end: '11:50', kind: 'breakout', title: 'Thematic Dialogue: Climate Justice & Grantmaking', detail: 'Samuel Okafor · Africa Climate Alliance', room: 'Conference Room B2', description: 'A facilitated partner exchange on equitable climate-finance practice.' }, { time: '12:00', end: '13:00', kind: 'workshop', title: 'Workshop: Measuring Long-term Change', detail: 'Dr. Ingrid Holm · Nordic Evaluation Centre', room: 'Workshop Room C', description: 'Bring one measurement challenge and leave with a peer-tested approach.' }, { time: '13:30', end: '14:30', kind: 'plenary', title: 'Partner Spotlight: Rights-Based Approaches', detail: 'Fatima Zahra Benali · MENA Rights Group', room: 'Main Hall A1', description: 'Case studies from partners implementing rights-based programmes.' }, { time: '14:45', end: '15:30', kind: 'breakout', title: 'Digital Rights in Authoritarian Contexts', detail: 'Lina Wei · Digital Frontiers Institute', room: 'Conference Room D1', description: 'A closed working session on safe and resilient digital-rights practice.' }, { time: '18:00', end: '20:00', kind: 'social', title: 'Welcome Reception & Dinner', detail: 'All participants', room: 'Rooftop Terrace', description: 'Informal networking and hosted dinner.' }],
  2: [{ time: '08:30', end: '09:30', kind: 'plenary', title: 'Learning Across the Portfolio', detail: 'OAK Programme Team', room: 'Main Hall A', description: 'Portfolio-level learning and the themes partners want to carry forward.' }, { time: '10:00', end: '11:15', kind: 'workshop', title: 'Peer Clinic: Partnership Design', detail: 'Facilitated working groups', room: 'Workshop Room C', description: 'Small-group clinics for live partnership-design questions.' }, { time: '13:30', end: '14:45', kind: 'breakout', title: 'Regional Collaboration Labs', detail: 'Partner-led sessions', room: 'Conference Rooms B2 & D1', description: 'Regional groups identify shared priorities and concrete next steps.' }, { time: '17:30', end: '19:00', kind: 'social', title: 'Partner Networking Evening', detail: 'All participants', room: 'Garden Terrace', description: 'An informal peer networking session.' }],
  3: [{ time: '09:00', end: '10:15', kind: 'plenary', title: 'Commitments for Collective Action', detail: 'Partner representatives', room: 'Main Hall A', description: 'Partners share collective commitments emerging from the convening.' }, { time: '10:45', end: '12:00', kind: 'workshop', title: 'Action Planning Workshop', detail: 'OAK Programme Team', room: 'Workshop Room C', description: 'Turn key discussions into accountable next actions.' }, { time: '13:30', end: '14:30', kind: 'plenary', title: 'Closing Session', detail: 'OAK Foundation', room: 'Main Hall A', description: 'Closing reflections, follow-up process, and departures.' }],
};
const resources = ['Opening Plenary Presentation', 'OAK Portfolio Overview 2026–28', 'Action Planning Worksheet', 'Partner Contact Directory', 'Photo Gallery: Day 1'];
const badge = (kind) => ({ breakout: 'Breakout', workshop: 'Workshop', plenary: 'Plenary', social: 'Social' }[kind]);

export default function ProgramPage() { const [tab, setTab] = useState('schedule'); const [day, setDay] = useState(1); const [notes, setNotes] = useState([]); return <div className="reference-page"><main className="programme-reference"><header className="programme-header"><h1>Programme</h1><p>OAK Partner Convening 2026</p><div className="programme-tabs"><button className={tab === 'schedule' ? 'active' : ''} onClick={() => setTab('schedule')}>Schedule</button><button className={tab === 'docs' ? 'active' : ''} onClick={() => setTab('docs')}>Docs</button></div></header>{tab === 'schedule' ? <Schedule day={day} setDay={setDay} /> : <Documents notes={notes} setNotes={setNotes} />}</main></div>; }

function Schedule({ day, setDay }) { const [open, setOpen] = useState(null); const items = programmes[day]; const featured = day === 1 ? items[0] : null; const sessions = featured ? items.slice(1) : items; const quiet = day === 1 ? [{ time: '08:00', title: 'Registration & Welcome Coffee' }, { time: '10:30', title: 'Coffee Break' }, { time: '12:00', title: 'Networking Lunch' }] : []; return <><section className="programme-days">{[1, 2, 3].map(number => <button key={number} onClick={() => { setDay(number); setOpen(null); }} className={day === number ? 'active' : ''}><small>{number === 1 ? 'MON' : number === 2 ? 'TUE' : 'WED'}</small><strong>Day {number}</strong><span>{8 + number} Mar</span></button>)}</section>{featured && <section className="featured-session"><small>★ FEATURED &nbsp;&nbsp; · &nbsp;&nbsp; {featured.time}–{featured.end}</small><h2>{featured.title}</h2><p>{featured.detail}</p><span><MapPin /> {featured.room}</span></section>}<div className="programme-legend"><span className="plenary">● Plenary</span><span className="breakout">● Breakout</span><span className="workshop">● Workshop</span><span className="social">● Social</span></div><section className="timeline">{sessions.map((item, index) => <React.Fragment key={item.title}>{quiet[index] && <div className="quiet-item"><time>{quiet[index].time}</time><span>{quiet[index].title}</span></div>}<button className="agenda-card" onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}><time>{item.time}<small>–{item.end}</small></time><div><h3>{item.title}</h3><p>{item.detail}</p><span><MapPin /> {item.room}</span>{open === index && <p className="agenda-description">{item.description}</p>}</div><em className={item.kind}>{badge(item.kind)} <ChevronDown /></em></button></React.Fragment>)}</section></>; }

function Documents({ notes, setNotes }) { const [draft, setDraft] = useState(''); const addNote = () => { if (!draft.trim()) return; setNotes(items => [{ title: 'You', body: draft.trim() }, ...items]); setDraft(''); }; const downloadResource = (resource) => { const url = URL.createObjectURL(new Blob([`${resource}\nOAK Partner Convening 2026`], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `${resource.replaceAll(' ', '-').toLowerCase()}.txt`; link.click(); URL.revokeObjectURL(url); }; return <section className="docs-view"><div className="docs-heading"><span><FileText /> Session Notes</span><button onClick={addNote}>+ Add note</button></div><label className="note-entry"><input value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => event.key === 'Enter' && addNote()} placeholder="Share a session note" /></label>{notes.length ? notes.map((note, index) => <article className="note-card" key={`${note.title}-${index}`}><span className="note-avatar">Y</span><div><strong>{note.title}</strong><small>Just now</small><p>{note.body}</p></div></article>) : <p className="empty-notes">No notes yet — add one for your team.</p>}<div className="docs-section-title"><Image /> Photo Gallery <small>6 photos</small></div><div className="photo-grid">{Array.from({ length: 6 }, (_, index) => <button className={`photo photo-${index + 1}`} key={index} aria-label={`Open event photo ${index + 1}`} onClick={() => window.alert(`Event photo ${index + 1} is available in the downloadable gallery.`)} />)}</div><div className="docs-section-title"><NotebookPen /> Key Takeaways</div><article className="takeaways">{['Shared learning infrastructure is the most requested resource across the convening.', 'Digital rights must be integrated into all programme areas, not siloed.', 'Peer exchange is the most valued support across OAK’s NGO network.'].map(item => <p key={item}>● <span>{item}</span></p>)}</article><div className="docs-section-title"><FileText /> Resources</div><div className="resource-list">{resources.map((resource, index) => <button key={resource} onClick={() => downloadResource(resource)}><FileText /><span><strong>{resource}</strong><small>{index === 4 ? '12 photos · added today' : 'PDF · 1.4 MB · added today'}</small></span><Download /></button>)}</div></section>; }
