import React, { useEffect, useMemo, useState } from 'react';
import { ChevronDown, FileText, MapPin, NotebookPen } from 'lucide-react';
import { event } from '../data/event';
import { getNotes, getSessions, saveNote } from '../lib/eventApi';
import { useAuth } from '../lib/auth';

const formatTime = (value) => new Intl.DateTimeFormat([], { hour: '2-digit', minute: '2-digit' }).format(new Date(value));
const formatDate = (value) => new Intl.DateTimeFormat([], { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(value));

export default function ProgramPage() {
  const { user } = useAuth(); const [sessions, setSessions] = useState([]); const [selected, setSelected] = useState(null); const [notes, setNotes] = useState([]); const [draft, setDraft] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getSessions(event.id).then((items) => { setSessions(items); setSelected(items[0] || null); }).catch((err) => setError(err.message)); }, []);
  useEffect(() => { if (selected) getNotes(selected.id).then(setNotes).catch((err) => setError(err.message)); else setNotes([]); }, [selected]);
  const groups = useMemo(() => sessions.reduce((all, item) => { const date = new Date(item.starts_at).toDateString(); (all[date] ||= []).push(item); return all; }, {}), [sessions]);
  const addNote = async () => { if (!draft.trim() || !selected || !user) return; try { const note = await saveNote(selected.id, user.id, draft.trim()); setNotes((items) => [note, ...items]); setDraft(''); } catch (err) { setError(err.message); } };
  return <div className="reference-page"><main className="programme-reference"><header className="programme-header"><h1>Programme</h1><p>{event.name}</p></header>{error && <p className="camera-error" role="alert">{error}</p>}{!sessions.length && !error && <p className="empty-notes">No sessions have been published yet.</p>}{Object.entries(groups).map(([date, items]) => <section className="timeline" key={date}><h2>{formatDate(items[0].starts_at)}</h2>{items.map((item) => <button className="agenda-card" key={item.id} onClick={() => setSelected(item)} aria-expanded={selected?.id === item.id}><time>{formatTime(item.starts_at)}<small>–{formatTime(item.ends_at)}</small></time><div><h3>{item.title}</h3><p>{item.speaker || 'Speaker to be confirmed'}</p><span><MapPin /> {item.venue || 'Venue to be confirmed'}</span>{selected?.id === item.id && item.description && <p className="agenda-description">{item.description}</p>}</div><em className="plenary">Session <ChevronDown /></em></button>)}</section>)}{selected && <section className="docs-view"><div className="docs-heading"><span><NotebookPen /> Personal notes: {selected.title}</span></div><label className="note-entry"><input value={draft} onChange={(item) => setDraft(item.target.value)} onKeyDown={(item) => item.key === 'Enter' && addNote()} placeholder="Add a private note for this session" /></label><button className="primary-button" onClick={addNote}>Save note</button>{notes.length ? notes.map((note) => <article className="note-card" key={note.id}><span className="note-avatar">Y</span><div><strong>You</strong><small>{new Intl.DateTimeFormat([], { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(note.created_at))}</small><p>{note.body}</p></div></article>) : <p className="empty-notes"><FileText /> No personal notes for this session.</p>}</section>}</main></div>;
}
